### ISSUE TITLE
Adversarial loss

### ISSUE THREAD

**Issue by andriiD** [VisionLearningGroup/DAL#1]
Thank you for sharing the code.
As I understood one of the classifiers should be trained with gradient reversal layer to extract class irrelevant features, same with domain discriminator (Feature_discriminator). But it looks like the gradient reversal layer is never used in the solver_disentangle.py. 
https://github.com/VisionLearningGroup/DAL/blob/e818c52e36fc701601eaf2f0ddf2ede82a1e6d2a/DAL_digits_release/model/svhn2mnist.py#L80

Feature discriminator doesn't have the gradient layer at all 
https://github.com/VisionLearningGroup/DAL/blob/master/DAL_digits_release/model/svhn2mnist.py#L40

Where is the gradient reversal layer applied to the features?

**Comment by Liyw979** [comment]
Why do you close the issus?I think you are right.

**Comment by jingzhengli** [comment]
> 

reverse=False
