### ISSUE TITLE
lack the data file mnist_data.pkl

### ISSUE THREAD

**Issue by xuChenSJTU** [VisionLearningGroup/DAL#3]
When I run the code follow your advice, it seems that you lack the mnist_data.pkl in the directory.

FileNotFoundError: [Errno 2] No such file or directory: './data/mnist_data.mat'

Could you upload the data please?
Thanks~

**Comment by buerzlh** [comment]
> When I run the code follow your advice, it seems that you lack the mnist_data.pkl in the directory.
> 
> FileNotFoundError: [Errno 2] No such file or directory: './data/mnist_data.mat'
> 
> Could you upload the data please?
> Thanks~

Hello, because of the lack of data sets, I have the same problem with you. Do you have a data set for this code now?

**Comment by Hangwei12358** [comment]
'mnistm_with_label.mat' is missing as well.

**Comment by dongshenggu** [comment]
'mnist_data.mat' is described on the previous repository "Maximum Classifier Discrepancy for Domain Adaptation", but still not found 'mnistm_with_label.mat'

**Comment by xcpeng** [comment]
Since many researchers have sent us emails for Digit-Five data. We share the Digit-Five dataset we use in our experiments in the following download link:

https://drive.google.com/open?id=1A4RJOFj4BJkmliiEL7g9WzNIDUHLxfmm

Keep in mind that the Mnist-M dataset is generated by ourselves, thus this subset may be different from the one released by DANN paper.

**Comment by dongshenggu** [comment]
> Since many researchers have sent us emails for Digit-Five data. We share the Digit-Five dataset we use in our experiments in the following download link:
> 
> https://drive.google.com/open?id=1A4RJOFj4BJkmliiEL7g9WzNIDUHLxfmm
> 
> Keep in mind that the Mnist-M dataset is generated by ourselves, thus this subset may be different from the one released by DANN paper.

Thanks very much!
