### ISSUE TITLE
Questions about MINE

### ISSUE THREAD

**Issue by geonyeong-park** [VisionLearningGroup/DAL#5]
This implementations seems having many flaws. I think Authors should clarify questions in previous issues clearly. In addition, using MINE part seems completely wrong, they introduced statistics network, but not optimizing it. Then Theoretically statistics networks is supposed to return estimated MI in totally meaningless way. Statistics network should be optimized in the way to raise up the lower bound of MI, while the estimated MI itself should be minimized with other part of networks. I'm not sure how the result in paper came out.

**Comment by xcpeng** [comment]
Hi, we are working on the code (with other researchers' help) to make the code more readable and it has been improved from the initial submission. We appreciate your mention of the MINE and we will take some time to look into it.
